In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('ailerons_train.csv')

In [3]:
df

,climbRate,Sgz,p,q,curPitch,curRoll,absRoll,diffClb,diffRollRate,diffDiffClb,...,diffSeTime8,diffSeTime9,diffSeTime10,diffSeTime11,diffSeTime12,diffSeTime13,diffSeTime14,alpha,Se,goal
0,2,-56,-0.33,-0.09,0.90,0.2,-11,12,0.004,-0.1,...,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.9,0.032,-0.0009
1,470,-39,0.02,0.12,0.39,-0.6,-12,8,0.009,-1.6,...,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.9,0.034,-0.0011
2,165,4,0.14,0.14,0.78,0.4,-11,-9,-0.003,-0.2,...,0.0,0.000,0.0,0.0,0.0,0.000,0.0,1.0,0.034,-0.0012
3,-113,5,-0.12,0.11,1.06,0.6,-10,-7,-0.008,0.0,...,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.9,0.033,-0.0011
4,-411,-21,-0.17,0.07,1.33,-0.6,-11,0,0.002,0.1,...,0.0,0.000,0.0,0.0,0.0,-0.002,0.0,0.9,0.032,-0.0008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12245,448,39,0.21,0.05,0.14,-0.5,-8,-4,0.009,-0.1,...,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.5,0.019,-0.0007
12246,179,64,0.06,0.17,0.41,0.5,-8,-9,-0.010,-0.6,...,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.6,0.021,-0.0008
12247,65,66,-0.03,0.14,0.54,0.5,-7,-17,-0.010,0.4,...,0.0,0.001,0.0,0.0,0.0,0.000,0.0,0.6,0.021,-0.0007
12248,-22,66,-0.08,0.23,0.61,0.5,-8,-15,-0.010,-0.6,...,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.6,0.022,-0.0006
12249,-59,47,-0.04,0.07,0.61,-0.7,-9,-7,0.004,0.2,...,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.6,0.020,-0.0004

In [4]:
# check for null values.

df.isnull().sum()

climbRate       0
Sgz             0
p               0
q               0
curPitch        0
curRoll         0
absRoll         0
diffClb         0
diffRollRate    0
diffDiffClb     0
SeTime1         0
SeTime2         0
SeTime3         0
SeTime4         0
SeTime5         0
SeTime6         0
SeTime7         0
SeTime8         0
SeTime9         0
SeTime10        0
SeTime11        0
SeTime12        0
SeTime13        0
SeTime14        0
diffSeTime1     0
diffSeTime2     0
diffSeTime3     0
diffSeTime4     0
diffSeTime5     0
diffSeTime6     0
diffSeTime7     0
diffSeTime8     0
diffSeTime9     0
diffSeTime10    0
diffSeTime11    0
diffSeTime12    0
diffSeTime13    0
diffSeTime14    0
alpha           0
Se              0
goal            0
dtype: int64

In [5]:
# set the independent and target variable.

x = df.drop('goal',axis=1)
y = df['goal']

In [6]:
# remove all columns which have less variance in their data as they won't make meaningful contribution towards the target variable.

from sklearn.feature_selection import VarianceThreshold

const_filter = VarianceThreshold(threshold=0.0001)

x_filter = const_filter.fit_transform(x)

In [29]:
# so only eleven columns which have greater than 0.01 % variation in their data.

x_filter = pd.DataFrame(x_filter,columns=x[x.columns[const_filter.get_support(indices=True)]].columns)
x_filter.shape

(12250, 11)

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
import statsmodels.api as sm
from statsmodels.regression.linear_model import OLS
from sklearn.model_selection import cross_val_score

In [12]:
# polynomial function helps to increase the number of independent variables by factoring in the interaction effect among the variables.

from sklearn.preprocessing import PolynomialFeatures

In [14]:
poly_trans = PolynomialFeatures(degree=2)

poly_features = poly_trans.fit_transform(x_filter)

In [31]:
poly_trans.get_feature_names(input_features=x_filter.columns)

['1',
 'climbRate',
 'Sgz',
 'p',
 'q',
 'curPitch',
 'curRoll',
 'absRoll',
 'diffClb',
 'diffRollRate',
 'diffDiffClb',
 'alpha',
 'climbRate^2',
 'climbRate Sgz',
 'climbRate p',
 'climbRate q',
 'climbRate curPitch',
 'climbRate curRoll',
 'climbRate absRoll',
 'climbRate diffClb',
 'climbRate diffRollRate',
 'climbRate diffDiffClb',
 'climbRate alpha',
 'Sgz^2',
 'Sgz p',
 'Sgz q',
 'Sgz curPitch',
 'Sgz curRoll',
 'Sgz absRoll',
 'Sgz diffClb',
 'Sgz diffRollRate',
 'Sgz diffDiffClb',
 'Sgz alpha',
 'p^2',
 'p q',
 'p curPitch',
 'p curRoll',
 'p absRoll',
 'p diffClb',
 'p diffRollRate',
 'p diffDiffClb',
 'p alpha',
 'q^2',
 'q curPitch',
 'q curRoll',
 'q absRoll',
 'q diffClb',
 'q diffRollRate',
 'q diffDiffClb',
 'q alpha',
 'curPitch^2',
 'curPitch curRoll',
 'curPitch absRoll',
 'curPitch diffClb',
 'curPitch diffRollRate',
 'curPitch diffDiffClb',
 'curPitch alpha',
 'curRoll^2',
 'curRoll absRoll',
 'curRoll diffClb',
 'curRoll diffRollRate',
 'curRoll diffDiffClb',
 'curRoll alpha',
 'absRoll^2',
 'absRoll diffClb',
 'absRoll diffRollRate',
 'absRoll diffDiffClb',
 'absRoll alpha',
 'diffClb^2',
 'diffClb diffRollRate',
 'diffClb diffDiffClb',
 'diffClb alpha',
 'diffRollRate^2',
 'diffRollRate diffDiffClb',
 'diffRollRate alpha',
 'diffDiffClb^2',
 'diffDiffClb alpha',
 'alpha^2']

In [32]:
interaction_df = pd.DataFrame(poly_features,columns=poly_trans.get_feature_names(input_features=x_filter.columns))

In [33]:
interaction_df

,1,climbRate,Sgz,p,q,curPitch,curRoll,absRoll,diffClb,diffRollRate,...,diffClb^2,diffClb diffRollRate,diffClb diffDiffClb,diffClb alpha,diffRollRate^2,diffRollRate diffDiffClb,diffRollRate alpha,diffDiffClb^2,diffDiffClb alpha,alpha^2
0,1.0,2.0,-56.0,-0.33,-0.09,0.90,0.2,-11.0,12.0,0.004,...,144.0,0.048,-1.2,10.8,0.000016,-0.0004,0.0036,0.01,-0.09,0.81
1,1.0,470.0,-39.0,0.02,0.12,0.39,-0.6,-12.0,8.0,0.009,...,64.0,0.072,-12.8,7.2,0.000081,-0.0144,0.0081,2.56,-1.44,0.81
2,1.0,165.0,4.0,0.14,0.14,0.78,0.4,-11.0,-9.0,-0.003,...,81.0,0.027,1.8,-9.0,0.000009,0.0006,-0.0030,0.04,-0.20,1.00
3,1.0,-113.0,5.0,-0.12,0.11,1.06,0.6,-10.0,-7.0,-0.008,...,49.0,0.056,-0.0,-6.3,0.000064,-0.0000,-0.0072,0.00,0.00,0.81
4,1.0,-411.0,-21.0,-0.17,0.07,1.33,-0.6,-11.0,0.0,0.002,...,0.0,0.000,0.0,0.0,0.000004,0.0002,0.0018,0.01,0.09,0.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12245,1.0,448.0,39.0,0.21,0.05,0.14,-0.5,-8.0,-4.0,0.009,...,16.0,-0.036,0.4,-2.0,0.000081,-0.0009,0.0045,0.01,-0.05,0.25
12246,1.0,179.0,64.0,0.06,0.17,0.41,0.5,-8.0,-9.0,-0.010,...,81.0,0.090,5.4,-5.4,0.000100,0.0060,-0.0060,0.36,-0.36,0.36
12247,1.0,65.0,66.0,-0.03,0.14,0.54,0.5,-7.0,-17.0,-0.010,...,289.0,0.170,-6.8,-10.2,0.000100,-0.0040,-0.0060,0.16,0.24,0.36
12248,1.0,-22.0,66.0,-0.08,0.23,0.61,0.5,-8.0,-15.0,-0.010,...,225.0,0.150,9.0,-9.0,0.000100,0.0060,-0.0060,0.36,-0.36,0.36
12249,1.0,-59.0,47.0,-0.04,0.07,0.61,-0.7,-9.0,-7.0,0.004,...,49.0,-0.028,-1.4,-4.2,0.000016,0.0008,0.0024,0.04,0.12,0.36

In [34]:
x_train,x_test,y_train,y_test = train_test_split(interaction_df,y,test_size=0.2)

In [38]:
x = sm.add_constant(interaction_df)
lr_ols = OLS(y,x)
results = lr_ols.fit()

# print the summary
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   goal   R-squared:                       0.843
Model:                            OLS   Adj. R-squared:                  0.842
Method:                 Least Squares   F-statistic:                     847.9
Date:                Wed, 02 Mar 2022   Prob (F-statistic):               0.00
Time:                        13:25:35   Log-Likelihood:                 89679.
No. Observations:               12250   AIC:                        -1.792e+05
Df Residuals:                   12172   BIC:                        -1.786e+05
Df Model:                          77
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
1                           -0.0002   3.11e-05     -7.544      0.000      -0.000      -0.000
climbRate                 3.087e-07   1.99e-07      1.553      0.120   -8.08e-08    6.98e-07
Sgz                       9.711e-09   3.42e-07      0.028      0.977    -6.6e-07    6.79e-07
p                         3.631e-05   2.64e-05      1.374      0.170   -1.55e-05    8.81e-05
q                            0.0005      0.000      1.952      0.051   -2.09e-06       0.001
curPitch                     0.0001      0.000      0.548      0.584      -0.000       0.000
curRoll                  -2.547e-06   1.12e-05     -0.228      0.820   -2.44e-05    1.94e-05
absRoll                   2.852e-05   4.46e-06      6.390      0.000    1.98e-05    3.73e-05
diffClb                   6.183e-06   2.19e-06      2.823      0.005    1.89e-06    1.05e-05
diffRollRate                 0.0052      0.001      5.810      0.000       0.003       0.007
diffDiffClb               1.345e-05   1.38e-05      0.977      0.329   -1.35e-05    4.04e-05
alpha                        0.0002      0.000      0.942      0.346      -0.000       0.001
climbRate^2              -6.468e-10      7e-10     -0.924      0.356   -2.02e-09    7.26e-10
climbRate Sgz            -3.147e-09   1.84e-09     -1.710      0.087   -6.75e-09     4.6e-10
climbRate p              -2.055e-07   1.34e-07     -1.538      0.124   -4.67e-07    5.64e-08
climbRate q               1.892e-06   1.08e-06      1.747      0.081   -2.31e-07    4.01e-06
climbRate curPitch       -1.361e-06   1.37e-06     -0.994      0.320   -4.05e-06    1.32e-06
climbRate curRoll         -5.86e-08   5.76e-08     -1.017      0.309   -1.72e-07    5.44e-08
climbRate absRoll         6.638e-08   1.73e-08      3.837      0.000    3.25e-08       1e-07
climbRate diffClb         9.235e-09   1.06e-08      0.869      0.385   -1.16e-08    3.01e-08
climbRate diffRollRate    4.232e-06   4.22e-06      1.002      0.316   -4.04e-06    1.25e-05
climbRate diffDiffClb     9.388e-08    6.6e-08      1.423      0.155   -3.55e-08    2.23e-07
climbRate alpha           5.856e-07   1.33e-06      0.440      0.660   -2.02e-06    3.19e-06
Sgz^2                     2.833e-09   1.83e-09      1.550      0.121   -7.51e-10    6.42e-09
Sgz p                     1.166e-06   2.08e-07      5.617      0.000    7.59e-07    1.57e-06
Sgz q                    -4.444e-06   2.18e-06     -2.038      0.042   -8.72e-06   -1.71e-07
Sgz curPitch             -3.681e-06   1.94e-06     -1.895      0.058   -7.49e-06    1.27e-07
Sgz curRoll               8.627e-08   9.19e-08      0.939      0.348   -9.38e-08    2.66e-07
Sgz absRoll              -4.851e-08   3.04e-08     -1.593      0.111   -1.08e-07    1.12e-08
Sgz diffClb              -2.005e-08   1.96e-08     -1.023      0.306   -5.85e-08    1.84e-08
Sgz diffRollRate         -5.015e-07   7.05e-06     -0.071      0.943   -1.43e-05    1.33e-05
Sgz diffDiffClb          -2.449e-07    1.1e-07     -2.227      0.026   -4.61e-07   -2.94e-08
Sgz alpha                  3.22e-06    1.9e-06      1.693      0.091   -5.09e-07    6.95e-06
p^2                      -4.639e-06   1.32e-05     -0.353      0.724   -3.04e-05    2.11e-05
p q                          0.0002      0.000      1.556      0.120   -6.37e-05       0.001
p curPitch                  -0.0003      0.000     -2.087      0.037      -0.001   -1.76e-05
p curRoll                -1.574e-05   6.94e-06     -2.267      0.023   -2.94e-05   -2.13e-06
p absRoll                 2.329e-05   2.32e-06     10.018      0.000    1.87e-05    2.78e-05
p diffClb                 8.902e-07   1.43e-06      0.622      0.534   -1.91e-06    3.69e-06
p diffRollRate               0.0006      0.000      1.328      0.184      -0.000       0.002
p diffDiffClb             6.391e-06   8.01e-06      0.797      0.425   -9.32e-06    2.21e-05
p alpha                  -1.591e-05      0.000     -0.118      0.906      -0.000       0.000
q^2                          0.0029      0.001      3.685      0.000       0.001       0.005
q curPitch                   0.0026      0.001      2.430      0.015       0.001       0.005
q curRoll                -2.928e-05      7e-05     -0.418      0.676      -0.000       0.000
q absRoll                 3.134e-05   2.41e-05      1.298      0.194    -1.6e-05    7.87e-05
q diffClb                 2.662e-05   1.32e-05      2.019      0.043    7.79e-07    5.25e-05
q diffRollRate               0.0004      0.005      0.089      0.929      -0.009       0.010
q diffDiffClb                0.0002   8.16e-05      2.809      0.005    6.93e-05       0.000
q alpha                     -0.0033      0.001     -2.993      0.003      -0.005      -0.001
curPitch^2                  -0.0007      0.001     -1.058      0.290      -0.002       0.001
curPitch curRoll         -8.509e-05      6e-05     -1.418      0.156      -0.000    3.25e-05
curPitch absRoll          7.496e-05    1.8e-05      4.174      0.000    3.98e-05       0.000
curPitch diffClb          1.782e-05   1.09e-05      1.633      0.102   -3.56e-06    3.92e-05
curPitch diffRollRate        0.0014      0.004      0.331      0.741      -0.007       0.010
curPitch diffDiffClb         0.0001   6.89e-05      1.813      0.070   -1.02e-05       0.000
curPitch alpha               0.0011      0.001      0.835      0.404      -0.001       0.004
curRoll^2                 2.448e-06   2.01e-06      1.215      0.224    -1.5e-06     6.4e-06
curRoll absRoll           1.775e-06   9.79e-07      1.813      0.070   -1.44e-07    3.69e-06
curRoll diffClb          -6.769e-07   6.38e-07     -1.061      0.289   -1.93e-06    5.73e-07
curRoll diffRollRate         0.0003      0.000      1.337      0.181      -0.000       0.001
curRoll diffDiffClb      -5.495e-07   3.49e-06     -0.157      0.875   -7.39e-06    6.29e-06
curRoll alpha            -8.274e-06   5.88e-05     -0.141      0.888      -0.000       0.000
absRoll^2                 4.559e-07   2.27e-07      2.005      0.045    1.02e-08    9.02e-07
absRoll diffClb           2.532e-07   2.06e-07      1.228      0.220   -1.51e-07    6.58e-07
absRoll diffRollRate         0.0002   7.49e-05      3.293      0.001    9.98e-05       0.000
absRoll diffDiffClb        9.52e-07   1.21e-06      0.789      0.430   -1.41e-06    3.32e-06
absRoll alpha            -8.076e-06   1.79e-05     -0.452      0.651   -4.31e-05    2.69e-05
diffClb^2                 2.577e-08   6.25e-08      0.412      0.680   -9.67e-08    1.48e-07
diffClb diffRollRate     -2.687e-05   4.59e-05     -0.585      0.558      -0.000    6.31e-05
diffClb diffDiffClb       1.004e-06   6.68e-07      1.503      0.133   -3.06e-07    2.31e-06
diffClb alpha            -3.003e-05    1.1e-05     -2.734      0.006   -5.16e-05    -8.5e-06
diffRollRate^2               0.0388      0.010      3.944      0.000       0.020       0.058
diffRollRate diffDiffClb    -0.0001      0.000     -0.604      0.546      -0.001       0.000
diffRollRate alpha          -0.0002      0.004     -0.044      0.965      -0.009       0.008
diffDiffClb^2             3.761e-06   2.25e-06      1.672      0.095   -6.48e-07    8.17e-06
diffDiffClb alpha           -0.0001   6.78e-05     -2.150      0.032      -0.000   -1.29e-05
alpha^2                     -0.0006      0.001     -0.933      0.351      -0.002       0.001
==============================================================================
Omnibus:                     1346.553   Durbin-Watson:                   1.782
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5243.097
Skew:                          -0.506   Prob(JB):                         0.00
Kurtosis:                       6.041   Cond. No.                     8.13e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.13e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

In [39]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.8443597595168136

In [40]:
np.mean(cross_val_score(lr,interaction_df,y,scoring='r2',cv=10))

0.8194890342519882